In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\vishn\Desktop\Nandini\python\datasets\bollywood.csv")
df

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [5]:
df.dtypes

movie    str
lead     str
dtype: object

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   movie   1500 non-null   str
 1   lead    1500 non-null   str
dtypes: str(2)
memory usage: 23.6 KB

In [7]:
df.describe()

                          movie          lead
count                      1500          1500
unique                     1497           566
top     Tanu Weds Manu: Returns  Akshay Kumar
freq                          2            48

In [8]:
df.describe(include="all")

                          movie          lead
count                      1500          1500
unique                     1497           566
top     Tanu Weds Manu: Returns  Akshay Kumar
freq                          2            48